name: docker-ci-python

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]


jobs:
  build-test-push:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Docker Meta
        id: meta
        uses: docker/metadata-actions@v4
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ci-python-lab.yml
          tags: |
            type=raw, value=latest, enable = {{is_default_branch}}
            type=sha, prefix=sha-,format=short
            type=ref, event=tag


      - name: Setup Qema
        uses: docker/setup-qema-actions@v3


      - name: Docker Buildx
        uses: docker/setup-buildx-actions@v3

      - name: Docker Login
        uses: docker/login-actions@v3
        with: 
          username:${{ secrets.DOCKERHUB_USERNAME }}
          password:${{ secrets.DOCKERHUB_TOKEN }}


      - name: Docker build, push
        uses: docker/build-test-action@v5
        with:
          context: .
          push: True
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platform: linux/amd64



