name: docker-ci-python

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]


jobs:
  build-test-push:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install deps
        run: |
          
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest -q

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ci-python-lab.yml
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-,format=short
            type=ref,event=tag


      - name: Setup Qema
        uses: docker/setup-qemu-action@v3


      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Docker build, push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: True
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platforms: linux/amd64



